name: Connect to GCP and List Instances

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]



jobs:
  setup-prepare-list:
    name: Setup, Prepare,
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configure Workload Identity Federation and generate an access token.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
     #     token_format: 'access_token'
          workload_identity_provider:  'projects/906266878830/locations/global/workloadIdentityPools/xyz-pool/providers/xyz-provider'
          service_account: 'xyz-sa@shivanvitha.iam.gserviceaccount.com'
 
